-- RESTAUBRUDDY SUPABASE SCHEMA

-- 1. Inventory Table
CREATE TABLE IF NOT EXISTS inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  name TEXT NOT NULL,
-- Create Inventory Table
CREATE TABLE inventory (
    id BIGSERIAL PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid(),
    name TEXT NOT NULL,
    quantity TEXT NOT NULL,
    price_per_unit DECIMAL(10,2) NOT NULL,
    expiry_date DATE NOT NULL,
    status TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Sales Logs Table
-- Create Sales Logs Table
CREATE TABLE sales_logs (
    id BIGSERIAL PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid(),
    date DATE NOT NULL,
    total_revenue DECIMAL(10,2) NOT NULL,
    customers INTEGER NOT NULL,
    dishes_sold JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. User Settings Table

-- Note: For simplicity in this demo, you can leave RLS disabled 
-- or create a policy that allows all operations for 'anon' role.
